# Generated by Django 2.2.6 on 2019-11-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='profilepic',
            field=models.FileField(default='doc_male.png', upload_to='doctor_app/img/'),
        ),
    ]
