# Generated by Django 2.2.6 on 2019-11-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_auto_20191112_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profilepic',
            field=models.FileField(default='doc_male.png', upload_to='doctor_app/assets/images/'),
        ),
    ]
