# Generated by Django 2.2.6 on 2019-11-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_auto_20191112_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profilepic',
            field=models.FileField(default='doc_male.png', upload_to='doctor_app/assets/images/'),
        ),
    ]
