# Generated by Django 2.2.6 on 2019-11-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0004_patient_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
